### ISSUE TITLE
Would like to remove Background Gradient 

### ISSUE THREAD

**Issue by kanjuo** [BlackrockDigital/startbootstrap-grayscale#105]
Hi I really love this template but the background gradient over the background image messes up with my image - i would like to remove the background gradient entirely or make it  less darker pls assist

**Comment by davidtmiller** [comment]
If you go into the CSS you will see the background gradient in the `.masthead` class. You can modify it there. If you are working from the source files in `src` then you can go to `src/scss/sections/_masthead.scss` and modify the gradient there.
