### ISSUE TITLE
h1, h2 not responsive

### ISSUE THREAD

**Issue by Th14go** [BlackrockDigital/startbootstrap-grayscale#116]
Good morning, congratulations for the beautiful project, I noticed a mistake in h1 and h2, it ends up leaving a white band on the side of the devices with smaller screen ex: iphone 5 / Se.
Example: https://prnt.sc/ncpqr1
Example removed h1,h2 : https://prnt.sc/ncppyu

**Comment by hgc42** [comment]
Try reducing the letter spacing. The following replacement code block in `css/grayscale.css` worked for me.

```
.masthead h1 {
  font-family: 'Varela Round';
  font-size: 2rem;
  line-height: 2.5rem;
  letter-spacing: 0.1rem;
  background: -webkit-linear-gradient(rgba(255, 255, 255, 0.9), rgba(255, 255, 255, 0));
  -webkit-text-fill-color: transparent;
  -webkit-background-clip: text;
}
```

Remember to reference the modified css in `index.html`.
```
  <link href="css/grayscale.css" rel="stylesheet">

```

**Comment by Th14go** [comment]
Thanks @hgc42 .
