### ISSUE TITLE
Navbar collapse not smooth with iPad

### ISSUE THREAD

**Issue by fgatin** [BlackrockDigital/startbootstrap-grayscale#32]
Hello,

I have tried opening my website on an iPad, and the collapsing of the navbar doesn't happen smoothly as it does on a computer. Basically I have to scroll down twice to see the collapsing happen. And I have to scroll to the top twice to see the navbar expand.
I have checked with the original grayscale preview and the same problem happens.

Any ideas?

Florent

**Comment by davidtmiller** [comment]
Not sure on this one, I'll have to test it on an iPad.

**Comment by davidtmiller** [comment]
This should be okay now...
