### ISSUE TITLE
Syntax errors in css and less files

### ISSUE THREAD

**Issue by caseyPav** [BlackrockDigital/startbootstrap-grayscale#39]
Line 193 of greyscale.css "0" is invalid syntax and should be  "0%"

Line 207 of greyscale.css "0" is invalid syntax and should be  "0%"

line 202 of greyscale.less "0" is invalid syntax and should be  "0%"

line 219 of greyscale.less "0" is invalid syntax and should be  "0%"

same errors exist in minified css

**Comment by davidtmiller** [comment]
I'll test this out soon, thanks!

**Comment by caseyPav** [comment]
Thanks! glad to help, thank you for providing such a nice learning tool...

**Comment by davidtmiller** [comment]
Fixed!
