### ISSUE TITLE
Unable to insert an image <img scr="">

### ISSUE THREAD

**Issue by marecgllmt** [BlackrockDigital/startbootstrap-grayscale#70]
Hi

I have a problem, i can't insert images in sections.

For exemple : a part of my index : 
`
    <section id="photoshop" class="photoshop-section content2-section text-center">
      <div class="container">
        <div class="col-lg-8 mx-auto">
          <h2>My photoshop creations</h2>
<br>
          <p><img scr="img/beimpressive.jpg" alt="Image1"/></p>
        </div>
      </div>
      <a href="#exit" class="btn btn-circle js-scroll-trigger">
                <i class="fa fa-angle-double-down animated"></i>
          </a>
    </section>`

Css sections involved : 
`.photoshop-section {
  color: white;
  background-color: grey;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover; } `
`.content2-section {
  padding-top: 75px;
  padding-bottom: 500px; }`

No matter which sections are involved, no picture appears.
What to do ?
Thank you

**Comment by lfallet** [comment]
It's probably just a typo ;-)
The HTML tag `img` has a `src` attribute, not `scr`
