### ISSUE TITLE
hoek 2.x alerts vulnerability issue  

### ISSUE THREAD

**Issue by cgvirus** [BlackrockDigital/startbootstrap-grayscale#82]
Hello, thanks for this template. Helped a lot to understand bootstrap properly. One thing is package-lock.json has a very old dependency of hoek. Which gives a vulnerability issue. 4.2 version has resolved the issue. Should we update it?
https://github.com/hapijs/hoek/issues/247

**Comment by davidtmiller** [comment]
I'll look into it. Since npm started adding in security reports at every install I have noticed lots of vulnerabilities but I just haven't had the bandwidth available in order to fix them all yet, but I will be getting to all of these eventually.

**Comment by davidtmiller** [comment]
Actually this one was quite easy, so it's been updated. Thanks!
