### ISSUE TITLE
Files I cannot seem to find

### ISSUE THREAD

**Issue by FEDevTP** [BlackrockDigital/startbootstrap-grayscale#95]
I'm using the ordinary version of the theme (didn't use npm), and I cannot find certain folders that are supposed to be inside the vendor folder according to chrome's inspect element, namely the scss folder. What am I doing wrong?

**Comment by davidtmiller** [comment]
If you run the default gulp task, or the vendor task, it should repopulate the vendor directory with the necessary files. They come with the package by default as well, so you could just re-download the theme as well.
